In [249]:
import numpy as np
import math
import time
n = 8

In [250]:
def estado_inicial(n = 8):
    ''' Seta o estado inicial de maneira randômica
    
        Arguments: n (int) -> número de rainhas
        Return: Matriz com as posições das rainhas como 1, e sem rainha como 0 
    '''
    
    matriz_inicial = np.zeros((n,n))
    random_indices = np.random.randint(n, size=n)
    
    for i, r in enumerate(random_indices):
        matriz_inicial[r, i] = 1
        
    return matriz_inicial.astype('int')

In [251]:
def custo_quadrado(estado, n):
    ''' Calcula o custo de matchs entre rainhas de uma determinada matriz
    
        Arguments:  estado (matriz int) -> Matriz com as posições das rainhas
                    n (int) -> número de rainhas
        Return: Float que representa o custo dessa matriz
    '''
    
    
    custo_diagonal = 0
    rainhas = np.argwhere(estado == 1)
    
    soma_hor = np.sum(estado, axis=1)
    
    for i, s in enumerate(soma_hor):
        soma_hor[i] = np.sum(np.arange(s))
    soma_hor = np.sum(soma_hor)
    
    for i in range(n):
        for j in range(i, n):
            x1, y1 = rainhas[i][0], rainhas[j][0]
            x2, y2 = rainhas[i][1], rainhas[j][1]
            if ((x1 + x2) == (y1 + y2) or (x1 - x2) == (y1 - y2)) and i!=j:
                custo_diagonal+=1
                
    return custo_diagonal+soma_hor

In [252]:
def matriz_custo_total(estado, n):
    ''' Calcula uma matriz custo de todas as possíveis movimentações
    
        Arguments:  estado (matriz int) -> Matriz com as posições das rainhas
                    n (int) -> númerzo de rainhas
        Return: Matriz custo de todas as possíveis movimentações 
    '''
    
    custo_total = np.zeros((n, n))
    estado_certo = estado.copy()
    
    for i in range(n):
        for j in range(n):
            estado[:, i] = 0
            estado[j][i] = 1
            custo_total[j][i] = custo_quadrado(estado, n)
        estado = estado_certo.copy()
        
    return custo_total

In [253]:
def hill_step(estado_atual, controle, n):
    ''' Realiza uma movimentação dado a melhor opção da matriz custo
    
        Arguments:  estado_atual (matriz int) -> Matriz com as posições das rainhas
                    controle (int) -> Variável que controla se o algoritmo deve ou não tomar uma decisão randômica
                    n (int) -> número de rainhas
        Return: Estado atual, custo atual e a variável controle
    '''
    
    matriz_custo = matriz_custo_total(estado_atual, n)
    rainhas = np.argwhere(estado_atual == 1)
    
    for r in rainhas:
        matriz_custo[r[0]][r[1]] = n*n

    valor_minimo = np.min(matriz_custo)
    indices_minimo = np.argwhere(matriz_custo == valor_minimo)
    choose_one = np.random.randint(len(indices_minimo))
    x, y = indices_minimo[choose_one]
    
    for r in rainhas:
        estado_atual[:, y] = 0
        estado_atual[x][y] = 1
        break

    custo_atual = custo_quadrado(estado_atual, n)
    
    if controle >= n:
        x, y = np.random.randint(0, n, size=2)
        estado_atual[:, y] = 0
        estado_atual[x][y] = 1
        controle = 0
    
    controle += 1
    
    return estado_atual, custo_atual, controle

In [254]:
def hill_climb(n):
    ''' Realiza uma sequência de passos até concluir o objetivo de posicionar as rainhas
    
        Arguments: n (int) -> número de rainhas
        Return: Estado Final com as rainhas posicionadas corretamente
    '''
    
    estado_atual = estado_inicial(n)
    custo_atual = custo_quadrado(estado_atual, n)
    controle = 0
    
    while custo_atual != 0:
        estado_atual, custo_atual, controle = hill_step(estado_atual, controle, n)
        print("Estado:\n{}\n\nCusto:\n{}\n\n".format(estado_atual, custo_atual))
        
    return estado_atual

In [255]:
i = 0
start_global = time.time()

while(i<10):
    start = time.time()
    estado_final = hill_climb(n)
    estado_final = estado_final.astype('int')
    print("Tempo de execução: {} (teste {})".format(time.time()-start, i))
    i+=1
    
print("Tempo Total: ", time.time()-start_global)

Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 0]]

Custo:
5


Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 0]]

Custo:
3


Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 0]]

Custo:
2


Estado:
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0]]

Custo:
3


Estado:
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 


Estado:
[[0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [1 0 1 0 0 0 0 0]]

Custo:
2


Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 


Estado:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]]

Custo:
3


Estado:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]]

Custo:
3


Estado:
[[0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0]]

Custo:
3


Estado:
[[0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 

Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0


Estado:
[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 1 0]]

Custo:
1


Estado:
[[0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]]

Custo:
1


Estado:
[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 